name: Nightly
on:
  push:
    branches: [ versioned-release ]
  pull_request:
    branches: [ versioned-release ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Set Nightly Release Version
        id: date
        run: echo "NIGHTLY_VERSION=$(date +'%Y.%m.%d').${env.GITHUB_SHA:0:6}-nightly" >> $env:GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Install dependencies
        run: dotnet restore
      - name: Download the file
        uses: suisei-cn/actions-download-file@v1 
        with:
          url: "https://cdn.discordapp.com/attachments/786130090102358017/786130170720682024/oo2core_8_win64.dll"
          target: ./CP77Tools/
      - name: Build
        run: dotnet build --configuration Release --no-restore -p:Version=${{ env.NIGHTLY_VERSION }}
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: artifact
          path: ./CP77Tools/bin/Release/net5.0
      - name: Prepare Release Artifact
        uses: papeloto/action-zip@v1
        with:
          files: ./CP77Tools/bin/Release/net5.0
          dest: nightly.zip
      - name: Deploy Nightly
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/WolvenKit/CP77Tools/releases/36240873/assets{?name,label} # find out this value by opening https://api.github.com/repos/<owner>/<repo>/releases in your browser and copy the full "upload_url" value including the {?name,label} part
          release_id: 36240873
          asset_path: nightly.zip
          asset_name: cp77tools-nightly-$$.zip
          asset_content_type: application/zip
